INSERT INTO EMPLOYEE VALUES ('1', '512','abc', 'engineer', 'abc@wipro.com');  
INSERT INTO EMPLOYEE VALUES ('2', '513','KLM', 'ENGINEER', 'KLM@WIPRO.COM');
INSERT INTO EMPLOYEE VALUES ('3', '514','XYZ', 'MANAGER', 'XYZ@WIPRO.COM');  