DROP TABLE IF EXISTS EMPLOYEE;  
CREATE TABLE EMPLOYEE (  
idNo int AUTO_INCREMENT ,
empId LONG AUTO_INCREMENT PRIMARY KEY ,  
empName VARCHAR(50) NOT NULL,  
empDes VARCHAR(50) NOT NULL,  
empEmail VARCHAR(50) NOT NULL
);  